# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.9b0]

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: 969779bb7df0db22f5ca47199863fc057f21a96c
    hooks:
      - id: autoflake
        stages: [commit]
        args: [--remove-all-unused-imports, --ignore-init-module-imports]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
        language_version: python3
        stages: [commit]

  - repo: local
    hooks:
      - id: pylint
        name: PyLint
        entry: pylint
        language: system
        files: \.py$
        stages: [commit]
        exclude: ^tests/
        args: [
          "-j 4",
          "-rn", # Only display messages
        ]
