name: 'Pre commit/pre push checks'

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      #----------------------------------------------
      # Run pre-commit
      #----------------------------------------------
      - uses: pre-commit/action@v2.0.3
